{"cells":[{"cell_type":"code","execution_count":1,"metadata":{},"outputs":[],"source":["import tensorflow as tf\n","from tensorflow import keras"]},{"cell_type":"code","execution_count":2,"metadata":{},"outputs":[],"source":["# Network and training\n","EPOCHS = 50\n","BATCH_SIZE = 128\n","VERBOSE = 1\n","NB_CLASSES = 10 # Number of outputs = number of digits\n","N_HIDDEN = 128\n","VALIDATION_SPLIT = 0.2 # how much TRAIN is reserved for VALIDATION"]},{"cell_type":"code","execution_count":3,"metadata":{},"outputs":[],"source":["# Loading MNIST dataset.\n","# Labels have one-hot representation.\n","mnist = keras.datasets.mnist\n","(X_train, Y_train), (X_test, Y_test) = mnist.load_data()"]},{"cell_type":"code","execution_count":4,"metadata":{},"outputs":[],"source":["# X_train is 60000 rows of 28x28 values; we reshape it to 60000 x 784.\n","RESHAPED = 784"]},{"cell_type":"code","execution_count":5,"metadata":{},"outputs":[],"source":["X_train = X_train.reshape(60000, RESHAPED)\n","X_test = X_test.reshape(10000, RESHAPED)\n","X_train = X_train.astype('float32')\n","X_test = X_test.astype('float32')"]},{"cell_type":"code","execution_count":6,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["60000 train samples\n","10000 test samples\n"]}],"source":["# Normalize inputs to be within in [0, 1].\n","X_train, X_test = X_train / 255.0, X_test / 255.0\n","print(X_train.shape[0], 'train samples')\n","print(X_test.shape[0], 'test samples')"]},{"cell_type":"code","execution_count":7,"metadata":{},"outputs":[],"source":["# Labels have one-hot representaion.\n","Y_train = tf.keras.utils.to_categorical(Y_train, NB_CLASSES)\n","Y_test = tf.keras.utils.to_categorical(Y_test, NB_CLASSES)"]},{"cell_type":"code","execution_count":8,"metadata":{},"outputs":[],"source":["# Build the model.\n","model = tf.keras.models.Sequential()\n","model.add(keras.layers.Dense(N_HIDDEN,\n","                             input_shape=(RESHAPED,),\n","                             name='dense_layer',\n","                             activation='relu'))\n","model.add(keras.layers.Dense(N_HIDDEN,\n","                             name='dense_layer_2',\n","                             activation='relu'))\n","model.add(keras.layers.Dense(N_HIDDEN,\n","                             name='dense_layer_3',\n","                             activation='softmax'))"]},{"cell_type":"code","execution_count":9,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["Model: \"sequential\"\n","_________________________________________________________________\n"," Layer (type)                Output Shape              Param #   \n","=================================================================\n"," dense_layer (Dense)         (None, 128)               100480    \n","                                                                 \n"," dense_layer_2 (Dense)       (None, 128)               16512     \n","                                                                 \n"," dense_layer_3 (Dense)       (None, 128)               16512     \n","                                                                 \n","=================================================================\n","Total params: 133504 (521.50 KB)\n","Trainable params: 133504 (521.50 KB)\n","Non-trainable params: 0 (0.00 Byte)\n","_________________________________________________________________\n"]}],"source":["# Summary of the model\n","model.summary()"]},{"cell_type":"code","execution_count":10,"metadata":{},"outputs":[],"source":["# Compiling the model\n","model.compile(optimizer='SGD',\n","              loss='categorical_crossentropy',\n","              metrics=['accuracy'])"]},{"cell_type":"code","execution_count":11,"metadata":{},"outputs":[{"data":{"text/plain":["60000"]},"execution_count":11,"metadata":{},"output_type":"execute_result"}],"source":["X_train.shape[0]"]},{"cell_type":"code","execution_count":12,"metadata":{},"outputs":[{"data":{"text/plain":["60000"]},"execution_count":12,"metadata":{},"output_type":"execute_result"}],"source":["Y_train.shape[0]"]},{"cell_type":"code","execution_count":13,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["Epoch 1/50\n"]},{"ename":"ValueError","evalue":"in user code:\n\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1338, in train_function  *\n        return step_function(self, iterator)\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1322, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1303, in run_step  **\n        outputs = model.train_step(data)\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1081, in train_step\n        loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1139, in compute_loss\n        return self.compiled_loss(\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\engine\\compile_utils.py\", line 265, in __call__\n        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\losses.py\", line 142, in __call__\n        losses = call_fn(y_true, y_pred)\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\losses.py\", line 268, in call  **\n        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\losses.py\", line 2122, in categorical_crossentropy\n        return backend.categorical_crossentropy(\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\backend.py\", line 5560, in categorical_crossentropy\n        target.shape.assert_is_compatible_with(output.shape)\n\n    ValueError: Shapes (128, 10) and (128, 128) are incompatible\n","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)","Cell \u001b[1;32mIn[13], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[39m# Training the model.\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m model\u001b[39m.\u001b[39;49mfit(X_train, Y_train,\n\u001b[0;32m      3\u001b[0m           batch_size\u001b[39m=\u001b[39;49mBATCH_SIZE, epochs\u001b[39m=\u001b[39;49mEPOCHS,\n\u001b[0;32m      4\u001b[0m           verbose\u001b[39m=\u001b[39;49mVERBOSE, validation_split\u001b[39m=\u001b[39;49mVALIDATION_SPLIT)\n","File \u001b[1;32mc:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     67\u001b[0m     filtered_tb \u001b[39m=\u001b[39m _process_traceback_frames(e\u001b[39m.\u001b[39m__traceback__)\n\u001b[0;32m     68\u001b[0m     \u001b[39m# To get the full stack trace, call:\u001b[39;00m\n\u001b[0;32m     69\u001b[0m     \u001b[39m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[1;32m---> 70\u001b[0m     \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mwith_traceback(filtered_tb) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39;00m\n\u001b[0;32m     71\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m     72\u001b[0m     \u001b[39mdel\u001b[39;00m filtered_tb\n","File \u001b[1;32m~\\AppData\\Local\\Temp\\__autograph_generated_filekgedlkb8.py:15\u001b[0m, in \u001b[0;36mouter_factory.<locals>.inner_factory.<locals>.tf__train_function\u001b[1;34m(iterator)\u001b[0m\n\u001b[0;32m     13\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m     14\u001b[0m     do_return \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[1;32m---> 15\u001b[0m     retval_ \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mconverted_call(ag__\u001b[39m.\u001b[39mld(step_function), (ag__\u001b[39m.\u001b[39mld(\u001b[39mself\u001b[39m), ag__\u001b[39m.\u001b[39mld(iterator)), \u001b[39mNone\u001b[39;00m, fscope)\n\u001b[0;32m     16\u001b[0m \u001b[39mexcept\u001b[39;00m:\n\u001b[0;32m     17\u001b[0m     do_return \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n","\u001b[1;31mValueError\u001b[0m: in user code:\n\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1338, in train_function  *\n        return step_function(self, iterator)\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1322, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1303, in run_step  **\n        outputs = model.train_step(data)\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1081, in train_step\n        loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1139, in compute_loss\n        return self.compiled_loss(\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\engine\\compile_utils.py\", line 265, in __call__\n        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\losses.py\", line 142, in __call__\n        losses = call_fn(y_true, y_pred)\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\losses.py\", line 268, in call  **\n        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\losses.py\", line 2122, in categorical_crossentropy\n        return backend.categorical_crossentropy(\n    File \"c:\\Users\\sahuanu\\AppData\\Local\\anaconda3\\envs\\tensorflowproj\\Lib\\site-packages\\keras\\src\\backend.py\", line 5560, in categorical_crossentropy\n        target.shape.assert_is_compatible_with(output.shape)\n\n    ValueError: Shapes (128, 10) and (128, 128) are incompatible\n"]}],"source":["# Training the model.\n","model.fit(X_train, Y_train,\n","          batch_size=BATCH_SIZE, epochs=EPOCHS,\n","          verbose=VERBOSE, validation_split=VALIDATION_SPLIT)"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":[]}],"metadata":{"kernelspec":{"display_name":"tensorflowproj","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.11.4"},"orig_nbformat":4},"nbformat":4,"nbformat_minor":2}
